/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StefanyActSafe;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author stefanybento
 */
public class ActSafeGUI extends javax.swing.JFrame {  
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ActSafeGUI.class.getName());
    private ActSafe alertSection;
    private ActSafe locatorSection;
    private ActSafe damageSection;

    /**
     * Creates new form ActSafeForm
     */
    public ActSafeGUI() {
        initComponents();
        
        alertSection = new ActSafe("Alert System",
                "In-app notification for severe weather conditions");
        locatorSection = new ActSafe("Locator",
                "Find the nearest shelters in your county");
        damageSection = new ActSafe("Damage Log",
                "Report damages with photos and severity level");
        
        alertLBL.setText(alertSection.getName());
        locatorLBL.setText(locatorSection.getName());
        damageLBL.setText(damageSection.getName());
        
        alertDescLBL.setText("<html>" + alertSection.getDescription() + "</html>");
        locatorDescLBL.setText("<html>" + locatorSection.getDescription() + "</html>");
        damageDescLBL.setText("<html>" + damageSection.getDescription() + "</html>");
        
        severityGroup.add(lowRB);
        severityGroup.add(mediumRB);
        severityGroup.add(highRB);
    }
        

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
 

    /**
     * Helper to switch cards/pages.
     */
        

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        severityGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        MenuPanel = new javax.swing.JPanel();
        alertBT = new javax.swing.JButton();
        locatorBT = new javax.swing.JButton();
        damageBT = new javax.swing.JButton();
        exitBT = new javax.swing.JButton();
        menuLBL = new javax.swing.JLabel();
        panelDamage = new javax.swing.JPanel();
        locationLBL = new javax.swing.JLabel();
        locationTF = new javax.swing.JTextField();
        descriptionLBL = new javax.swing.JLabel();
        descriptionSCROLL = new javax.swing.JScrollPane();
        descriptionTA = new javax.swing.JTextArea();
        submitBT = new javax.swing.JButton();
        damageLBL = new javax.swing.JLabel();
        choosePhotoBT = new javax.swing.JButton();
        photoPreviewLBL = new javax.swing.JLabel();
        damagemenuBT = new javax.swing.JButton();
        lowRB = new javax.swing.JRadioButton();
        mediumRB = new javax.swing.JRadioButton();
        highRB = new javax.swing.JRadioButton();
        damageDescLBL = new javax.swing.JLabel();
        panelLocator = new javax.swing.JPanel();
        searchLBL = new javax.swing.JLabel();
        searchTF = new javax.swing.JTextField();
        shelterLBL = new javax.swing.JLabel();
        shelterBT = new javax.swing.JButton();
        locatormenuBT = new javax.swing.JButton();
        shelterScrollPane2 = new javax.swing.JScrollPane();
        shelterTA = new javax.swing.JTextArea();
        locatorDescLBL = new javax.swing.JLabel();
        locatorLBL = new javax.swing.JLabel();
        panelAlert = new javax.swing.JPanel();
        weatherConditionLBL = new javax.swing.JLabel();
        severityLBL = new javax.swing.JLabel();
        severityCB = new javax.swing.JComboBox<>();
        sendalertBT = new javax.swing.JButton();
        alertLBL = new javax.swing.JLabel();
        alertmenuBT = new javax.swing.JButton();
        weatherConditionCB = new javax.swing.JComboBox<>();
        alertScrollPane1 = new javax.swing.JScrollPane();
        alertTA = new javax.swing.JTextArea();
        alertDescLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        alertBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AlertSystem.png"))); // NOI18N
        alertBT.setBorder(null);
        alertBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertBTActionPerformed(evt);
            }
        });

        locatorBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Locator.png"))); // NOI18N
        locatorBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locatorBTActionPerformed(evt);
            }
        });

        damageBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DamageLog.png"))); // NOI18N
        damageBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                damageBTActionPerformed(evt);
            }
        });

        exitBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EXIT.png"))); // NOI18N
        exitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTActionPerformed(evt);
            }
        });

        menuLBL.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 24)); // NOI18N
        menuLBL.setText("MENU");

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(menuLBL))
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(damageBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alertBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(locatorBT)
                            .addComponent(exitBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(menuLBL)
                .addGap(10, 10, 10)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(locatorBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alertBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitBT)
                    .addComponent(damageBT))
                .addGap(26, 26, 26))
        );

        mainPanel.add(MenuPanel, "card5");

        panelDamage.setBackground(new java.awt.Color(220, 238, 232));

        locationLBL.setText("Location:");

        locationTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationTFActionPerformed(evt);
            }
        });

        descriptionLBL.setText("Description:");

        descriptionTA.setColumns(20);
        descriptionTA.setRows(5);
        descriptionSCROLL.setViewportView(descriptionTA);

        submitBT.setText("Submit Damage");
        submitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBTActionPerformed(evt);
            }
        });

        damageLBL.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        damageLBL.setText("Damage Log");

        choosePhotoBT.setText("Choose Photo");
        choosePhotoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosePhotoBTActionPerformed(evt);
            }
        });

        photoPreviewLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photoPreviewLBL.setText("Preview");
        photoPreviewLBL.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        photoPreviewLBL.setPreferredSize(new java.awt.Dimension(150, 150));

        damagemenuBT.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        damagemenuBT.setText("MENU");
        damagemenuBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                damagemenuBTActionPerformed(evt);
            }
        });

        lowRB.setText("Low");

        mediumRB.setText("Medium");
        mediumRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumRBActionPerformed(evt);
            }
        });

        highRB.setText("High");
        highRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highRBActionPerformed(evt);
            }
        });

        damageDescLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        damageDescLBL.setText("...");

        javax.swing.GroupLayout panelDamageLayout = new javax.swing.GroupLayout(panelDamage);
        panelDamage.setLayout(panelDamageLayout);
        panelDamageLayout.setHorizontalGroup(
            panelDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDamageLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(choosePhotoBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitBT)
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDamageLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(photoPreviewLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(panelDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDamageLayout.createSequentialGroup()
                        .addGroup(panelDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descriptionSCROLL, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locationTF, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDamageLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(descriptionLBL))
                            .addGroup(panelDamageLayout.createSequentialGroup()
                                .addComponent(lowRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mediumRB)
                                .addGap(18, 18, 18)
                                .addComponent(highRB)))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDamageLayout.createSequentialGroup()
                        .addComponent(locationLBL)
                        .addGap(84, 84, 84))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDamageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(damageLBL)
                .addGap(168, 168, 168))
            .addGroup(panelDamageLayout.createSequentialGroup()
                .addGroup(panelDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDamageLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(damagemenuBT))
                    .addGroup(panelDamageLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(damageDescLBL)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDamageLayout.setVerticalGroup(
            panelDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDamageLayout.createSequentialGroup()
                .addComponent(damageLBL)
                .addGap(16, 16, 16)
                .addComponent(damageDescLBL)
                .addGap(18, 18, 18)
                .addGroup(panelDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDamageLayout.createSequentialGroup()
                        .addComponent(locationLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(locationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lowRB)
                            .addComponent(mediumRB)
                            .addComponent(highRB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descriptionLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descriptionSCROLL, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(photoPreviewLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choosePhotoBT)
                    .addComponent(submitBT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(damagemenuBT)
                .addGap(17, 17, 17))
        );

        mainPanel.add(panelDamage, "card2");

        panelLocator.setBackground(new java.awt.Color(245, 241, 241));

        searchLBL.setText("Enter County:");

        searchTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTFActionPerformed(evt);
            }
        });

        shelterLBL.setText("Nearest Shelter:");

        shelterBT.setText("Find Shelter");
        shelterBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shelterBTActionPerformed(evt);
            }
        });

        locatormenuBT.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        locatormenuBT.setText("MENU");
        locatormenuBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locatormenuBTActionPerformed(evt);
            }
        });

        shelterTA.setEditable(false);
        shelterTA.setColumns(20);
        shelterTA.setLineWrap(true);
        shelterTA.setRows(5);
        shelterTA.setWrapStyleWord(true);
        shelterScrollPane2.setViewportView(shelterTA);

        locatorDescLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        locatorDescLBL.setText("...");

        locatorLBL.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        locatorLBL.setText("Locator");

        javax.swing.GroupLayout panelLocatorLayout = new javax.swing.GroupLayout(panelLocator);
        panelLocator.setLayout(panelLocatorLayout);
        panelLocatorLayout.setHorizontalGroup(
            panelLocatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLocatorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(locatormenuBT)
                .addGap(179, 179, 179))
            .addGroup(panelLocatorLayout.createSequentialGroup()
                .addGroup(panelLocatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLocatorLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panelLocatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shelterScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLocatorLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(panelLocatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchLBL)
                                    .addComponent(shelterLBL))
                                .addGap(23, 23, 23)
                                .addGroup(panelLocatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(shelterBT, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(locatorLBL)))))
                    .addGroup(panelLocatorLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(locatorDescLBL)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelLocatorLayout.setVerticalGroup(
            panelLocatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLocatorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(locatorLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(locatorDescLBL)
                .addGap(27, 27, 27)
                .addGroup(panelLocatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLBL)
                    .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLocatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shelterLBL)
                    .addComponent(shelterBT))
                .addGap(36, 36, 36)
                .addComponent(shelterScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(locatormenuBT)
                .addGap(18, 18, 18))
        );

        mainPanel.add(panelLocator, "card3");

        panelAlert.setBackground(new java.awt.Color(245, 226, 207));

        weatherConditionLBL.setText("Weather condition:");

        severityLBL.setText("Severity:");

        severityCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "High" }));
        severityCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                severityCBActionPerformed(evt);
            }
        });

        sendalertBT.setText("Send Alert");
        sendalertBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendalertBTActionPerformed(evt);
            }
        });

        alertLBL.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        alertLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alertLBL.setText("Alert");

        alertmenuBT.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        alertmenuBT.setText("MENU");
        alertmenuBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertmenuBTActionPerformed(evt);
            }
        });

        weatherConditionCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one option", "Storm", "Flood", "Snow/Ice" }));

        alertTA.setColumns(20);
        alertTA.setRows(5);
        alertScrollPane1.setViewportView(alertTA);

        alertDescLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alertDescLBL.setText("...");

        javax.swing.GroupLayout panelAlertLayout = new javax.swing.GroupLayout(panelAlert);
        panelAlert.setLayout(panelAlertLayout);
        panelAlertLayout.setHorizontalGroup(
            panelAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlertLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(alertLBL)
                .addGap(198, 198, 198))
            .addGroup(panelAlertLayout.createSequentialGroup()
                .addGroup(panelAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlertLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(alertmenuBT))
                    .addGroup(panelAlertLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(panelAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(severityLBL)
                            .addComponent(weatherConditionLBL))
                        .addGap(33, 33, 33)
                        .addGroup(panelAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(weatherConditionCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(severityCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelAlertLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(sendalertBT))
                    .addGroup(panelAlertLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(alertScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAlertLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(alertDescLBL)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelAlertLayout.setVerticalGroup(
            panelAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlertLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(alertLBL)
                .addGap(7, 7, 7)
                .addComponent(alertDescLBL)
                .addGap(28, 28, 28)
                .addGroup(panelAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(weatherConditionLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weatherConditionCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(severityCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(severityLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendalertBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alertScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alertmenuBT)
                .addGap(12, 12, 12))
        );

        mainPanel.add(panelAlert, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void severityCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_severityCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_severityCBActionPerformed

    private void shelterBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shelterBTActionPerformed
        // TODO add your handling code here:
        Locator locator = new Locator();
        String shelterInfo = locator.findShelterByCounty(searchTF.getText());
        
        shelterTA.setText(shelterInfo);
    }//GEN-LAST:event_shelterBTActionPerformed

    private void locationTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationTFActionPerformed

    private void submitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBTActionPerformed
        // TODO add your handling code here:
        String loc = locationTF.getText();
        String desc = descriptionTA.getText();
        
        // display message to user
        JOptionPane.showMessageDialog(null, "Damage submitted!\nLocation: " + loc + "\nDescription: " + desc);
    }//GEN-LAST:event_submitBTActionPerformed

    private void sendalertBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendalertBTActionPerformed
        // TODO add your handling code here:
        String condition = ((String)weatherConditionCB.getSelectedItem()).trim();
        String severity = (String) severityCB.getSelectedItem();
        
        if (condition== null || condition.isEmpty()){
            alertTA.setText("Please enter a weather condition (e.g. Storm, Flood).");
            return;
        }
        
        AlertSystem alert = new AlertSystem(condition, severity);
        
        alertTA.setText(alert.getNotificationsText());
        
    }//GEN-LAST:event_sendalertBTActionPerformed

    private void searchTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTFActionPerformed

    private void choosePhotoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosePhotoBTActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(null);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            ImageIcon icon = new ImageIcon(file.getAbsolutePath());
            
            Image scaled = icon.getImage().getScaledInstance(
                    photoPreviewLBL.getWidth(),
                    photoPreviewLBL.getHeight(),
                    Image.SCALE_SMOOTH
            );
            
            photoPreviewLBL.setIcon(new ImageIcon(scaled));
            photoPreviewLBL.setText("");
        }
    }//GEN-LAST:event_choosePhotoBTActionPerformed

    private void damagemenuBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_damagemenuBTActionPerformed
        // TODO add your handling code here:
        panelAlert.setVisible(false);
        panelLocator.setVisible(false);
        panelDamage.setVisible(false);
        MenuPanel.setVisible(true);
    }//GEN-LAST:event_damagemenuBTActionPerformed

    private void locatormenuBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locatormenuBTActionPerformed
        // TODO add your handling code here:
        panelAlert.setVisible(false);
        panelLocator.setVisible(false);
        panelDamage.setVisible(false);
        MenuPanel.setVisible(true);
    }//GEN-LAST:event_locatormenuBTActionPerformed

    private void alertBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertBTActionPerformed
        // TODO add your handling code here:
        panelAlert.setVisible(true);
        panelLocator.setVisible(false);
        panelDamage.setVisible(false);
        MenuPanel.setVisible(false);
        
    }//GEN-LAST:event_alertBTActionPerformed

    private void locatorBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locatorBTActionPerformed
        // TODO add your handling code here:
        panelAlert.setVisible(false);
        panelLocator.setVisible(true);
        panelDamage.setVisible(false);
        MenuPanel.setVisible(false);
    }//GEN-LAST:event_locatorBTActionPerformed

    private void damageBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_damageBTActionPerformed
        // TODO add your handling code here:
        panelAlert.setVisible(false);
        panelLocator.setVisible(false);
        panelDamage.setVisible(true);
        MenuPanel.setVisible(false);
    }//GEN-LAST:event_damageBTActionPerformed

    private void exitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTActionPerformed

    private void alertmenuBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertmenuBTActionPerformed
        // TODO add your handling code here:
        panelAlert.setVisible(false);
        panelLocator.setVisible(false);
        panelDamage.setVisible(false);
        MenuPanel.setVisible(true);
    }//GEN-LAST:event_alertmenuBTActionPerformed

    private void highRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_highRBActionPerformed

    private void mediumRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mediumRBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ActSafeGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JButton alertBT;
    private javax.swing.JLabel alertDescLBL;
    private javax.swing.JLabel alertLBL;
    private javax.swing.JScrollPane alertScrollPane1;
    private javax.swing.JTextArea alertTA;
    private javax.swing.JButton alertmenuBT;
    private javax.swing.JButton choosePhotoBT;
    private javax.swing.JButton damageBT;
    private javax.swing.JLabel damageDescLBL;
    private javax.swing.JLabel damageLBL;
    private javax.swing.JButton damagemenuBT;
    private javax.swing.JLabel descriptionLBL;
    private javax.swing.JScrollPane descriptionSCROLL;
    private javax.swing.JTextArea descriptionTA;
    private javax.swing.JButton exitBT;
    private javax.swing.JRadioButton highRB;
    private javax.swing.JLabel locationLBL;
    private javax.swing.JTextField locationTF;
    private javax.swing.JButton locatorBT;
    private javax.swing.JLabel locatorDescLBL;
    private javax.swing.JLabel locatorLBL;
    private javax.swing.JButton locatormenuBT;
    private javax.swing.JRadioButton lowRB;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton mediumRB;
    private javax.swing.JLabel menuLBL;
    private javax.swing.JPanel panelAlert;
    private javax.swing.JPanel panelDamage;
    private javax.swing.JPanel panelLocator;
    private javax.swing.JLabel photoPreviewLBL;
    private javax.swing.JLabel searchLBL;
    private javax.swing.JTextField searchTF;
    private javax.swing.JButton sendalertBT;
    private javax.swing.JComboBox<String> severityCB;
    private javax.swing.ButtonGroup severityGroup;
    private javax.swing.JLabel severityLBL;
    private javax.swing.JButton shelterBT;
    private javax.swing.JLabel shelterLBL;
    private javax.swing.JScrollPane shelterScrollPane2;
    private javax.swing.JTextArea shelterTA;
    private javax.swing.JButton submitBT;
    private javax.swing.JComboBox<String> weatherConditionCB;
    private javax.swing.JLabel weatherConditionLBL;
    // End of variables declaration//GEN-END:variables

}