/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package plansafe;

/**
 *
 * @author Dell
 */
public class ChecklistGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChecklistGUI.class.getName());

    /**
     * Creates new form PreparednessChecklistGUI
     */
    public ChecklistGUI() {
        initComponents();
        emptyP.setVisible(true);
        fireP.setVisible(false);
        floodP.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        titleLBL = new javax.swing.JLabel();
        fireRBTN = new javax.swing.JRadioButton();
        floodRBTN = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        checkBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        listLP = new javax.swing.JLayeredPane();
        emptyP = new javax.swing.JPanel();
        textLBL = new javax.swing.JLabel();
        fireP = new javax.swing.JPanel();
        fire1CB = new javax.swing.JCheckBox();
        fire2CB = new javax.swing.JCheckBox();
        fire3CB = new javax.swing.JCheckBox();
        fire4CB = new javax.swing.JCheckBox();
        fire5CB = new javax.swing.JCheckBox();
        floodP = new javax.swing.JPanel();
        flood1CB = new javax.swing.JCheckBox();
        flood2CB = new javax.swing.JCheckBox();
        flood3CB = new javax.swing.JCheckBox();
        flood4CB = new javax.swing.JCheckBox();
        flood5CB = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLBL.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        titleLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLBL.setText("Preparedness Checklist");

        buttonGroup1.add(fireRBTN);
        fireRBTN.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        fireRBTN.setForeground(new java.awt.Color(255, 0, 0));
        fireRBTN.setText("Fire Disaster");
        fireRBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fireRBTNActionPerformed(evt);
            }
        });

        buttonGroup1.add(floodRBTN);
        floodRBTN.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        floodRBTN.setForeground(new java.awt.Color(0, 51, 255));
        floodRBTN.setText("Flood Disaster");
        floodRBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floodRBTNActionPerformed(evt);
            }
        });

        displayTA.setColumns(20);
        displayTA.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        checkBTN.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        checkBTN.setText("CHECK");

        backBTN.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        backBTN.setText("BACK");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        exitBTN.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        exitBTN.setText("EXIT");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        textLBL.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        textLBL.setText("Please choose an disaster type to see the checklist");

        javax.swing.GroupLayout emptyPLayout = new javax.swing.GroupLayout(emptyP);
        emptyP.setLayout(emptyPLayout);
        emptyPLayout.setHorizontalGroup(
            emptyPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
            .addGroup(emptyPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(emptyPLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(textLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );
        emptyPLayout.setVerticalGroup(
            emptyPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
            .addGroup(emptyPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(emptyPLayout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(textLBL)
                    .addContainerGap(66, Short.MAX_VALUE)))
        );

        fireP.setForeground(new java.awt.Color(255, 255, 255));
        fireP.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N

        fire1CB.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        fire1CB.setText("Install and test smoke alarms.");

        fire2CB.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        fire2CB.setText("Prepare a fire extinguisher.");

        fire3CB.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        fire3CB.setText("Store important documents in a fireproof container.");

        fire4CB.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        fire4CB.setText("Building an emergency kit");

        fire5CB.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        fire5CB.setText("Create an escape plan");

        javax.swing.GroupLayout firePLayout = new javax.swing.GroupLayout(fireP);
        fireP.setLayout(firePLayout);
        firePLayout.setHorizontalGroup(
            firePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firePLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(firePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fire2CB)
                    .addComponent(fire4CB)
                    .addComponent(fire1CB)
                    .addComponent(fire3CB)
                    .addComponent(fire5CB))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        firePLayout.setVerticalGroup(
            firePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firePLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fire1CB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fire2CB)
                .addGap(5, 5, 5)
                .addComponent(fire3CB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fire4CB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fire5CB)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        flood1CB.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        flood1CB.setText("Elevate electrical appliances and outlets.");

        flood2CB.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        flood2CB.setText("Prepare sandbags or flood barriers.");

        flood3CB.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        flood3CB.setText("Prepare a “go-bag” with food, water, meds, and flashlight.");

        flood4CB.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        flood4CB.setText("Keep emergency supplies in a waterproof container.");

        flood5CB.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        flood5CB.setText("Know the nearest evacuation routes and high ground.");

        javax.swing.GroupLayout floodPLayout = new javax.swing.GroupLayout(floodP);
        floodP.setLayout(floodPLayout);
        floodPLayout.setHorizontalGroup(
            floodPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(floodPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(floodPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(floodPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(flood1CB)
                        .addComponent(flood2CB)
                        .addComponent(flood3CB, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(flood4CB)
                    .addComponent(flood5CB))
                .addContainerGap())
        );
        floodPLayout.setVerticalGroup(
            floodPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(floodPLayout.createSequentialGroup()
                .addComponent(flood1CB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flood2CB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flood3CB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flood4CB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flood5CB)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        listLP.setLayer(emptyP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        listLP.setLayer(fireP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        listLP.setLayer(floodP, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout listLPLayout = new javax.swing.GroupLayout(listLP);
        listLP.setLayout(listLPLayout);
        listLPLayout.setHorizontalGroup(
            listLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listLPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fireP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(listLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listLPLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(floodP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(listLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listLPLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(emptyP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        listLPLayout.setVerticalGroup(
            listLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listLPLayout.createSequentialGroup()
                .addComponent(fireP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
            .addGroup(listLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLPLayout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(floodP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(listLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listLPLayout.createSequentialGroup()
                    .addComponent(emptyP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBTN)
                            .addComponent(backBTN)
                            .addComponent(exitBTN))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listLP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(floodRBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(fireRBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(25, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(titleLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fireRBTN)
                        .addGap(18, 18, 18)
                        .addComponent(floodRBTN))
                    .addComponent(listLP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(checkBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(backBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fireRBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fireRBTNActionPerformed
        // TODO add your handling code here:
        fireP.setVisible(true);
        emptyP.setVisible(false);
        floodP.setVisible(false);
    }//GEN-LAST:event_fireRBTNActionPerformed

    private void floodRBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floodRBTNActionPerformed
        // TODO add your handling code here:
        fireP.setVisible(false);
        emptyP.setVisible(false);
        floodP.setVisible(true);
    }//GEN-LAST:event_floodRBTNActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        PlanSafeGUI pgui = new PlanSafeGUI();
        pgui.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_backBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ChecklistGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton checkBTN;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JPanel emptyP;
    private javax.swing.JButton exitBTN;
    private javax.swing.JCheckBox fire1CB;
    private javax.swing.JCheckBox fire2CB;
    private javax.swing.JCheckBox fire3CB;
    private javax.swing.JCheckBox fire4CB;
    private javax.swing.JCheckBox fire5CB;
    private javax.swing.JPanel fireP;
    private javax.swing.JRadioButton fireRBTN;
    private javax.swing.JCheckBox flood1CB;
    private javax.swing.JCheckBox flood2CB;
    private javax.swing.JCheckBox flood3CB;
    private javax.swing.JCheckBox flood4CB;
    private javax.swing.JCheckBox flood5CB;
    private javax.swing.JPanel floodP;
    private javax.swing.JRadioButton floodRBTN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLayeredPane listLP;
    private javax.swing.JLabel textLBL;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
