/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package plansafe;

/**
 *
 * @author Dell
 */
public class PlanSafeGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PlanSafeGUI.class.getName());

    /**
     * Creates new form PlanSafeGUI
     */
    public PlanSafeGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLBL = new javax.swing.JLabel();
        text1LBL = new javax.swing.JLabel();
        text2LBL = new javax.swing.JLabel();
        checklistBTN = new javax.swing.JButton();
        riskCalcBTN = new javax.swing.JButton();
        contactBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLBL.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        titleLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLBL.setText("PlanSafe");

        text1LBL.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        text1LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text1LBL.setText("This section will help you to prepare for fire and flood disaster.");

        text2LBL.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        text2LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text2LBL.setText("Please choose a subsection that will help you to plan ahead.");

        checklistBTN.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        checklistBTN.setText("Preparedness Checklist");
        checklistBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checklistBTNActionPerformed(evt);
            }
        });

        riskCalcBTN.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        riskCalcBTN.setText("Location Risk Calculator");
        riskCalcBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riskCalcBTNActionPerformed(evt);
            }
        });

        contactBTN.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        contactBTN.setText("Emergency Contact");
        contactBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactBTNActionPerformed(evt);
            }
        });

        backBTN.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        backBTN.setText("BACK");

        exitBTN.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        exitBTN.setText("EXIT");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(text1LBL, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
            .addComponent(text2LBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titleLBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(backBTN)
                .addGap(63, 63, 63)
                .addComponent(exitBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(riskCalcBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checklistBTN)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contactBTN)
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(titleLBL)
                .addGap(18, 18, 18)
                .addComponent(text1LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text2LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(riskCalcBTN)
                    .addComponent(checklistBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contactBTN)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBTN)
                    .addComponent(exitBTN))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void riskCalcBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riskCalcBTNActionPerformed
        // TODO add your handling code here:
        LocationRiskGUI lgui = new LocationRiskGUI();
        lgui.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_riskCalcBTNActionPerformed

    private void checklistBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checklistBTNActionPerformed
        // TODO add your handling code here:        
        ChecklistGUI cgui = new ChecklistGUI();
        cgui.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_checklistBTNActionPerformed

    private void contactBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactBTNActionPerformed
        // TODO add your handling code here:
        EmerContactGUI egui = new EmerContactGUI();
        egui.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_contactBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PlanSafeGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JButton checklistBTN;
    private javax.swing.JButton contactBTN;
    private javax.swing.JButton exitBTN;
    private javax.swing.JButton riskCalcBTN;
    private javax.swing.JLabel text1LBL;
    private javax.swing.JLabel text2LBL;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
