/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ActSafe;

import javax.swing.JOptionPane;


/**
 *
 * @author stefanybento
 */
public class ActSafeForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ActSafeForm.class.getName());

    /**
     * Creates new form ActSafeForm
     */
    public ActSafeForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAlert = new javax.swing.JPanel();
        alertmsgLBL = new javax.swing.JLabel();
        severityLBL = new javax.swing.JLabel();
        alertmsgTF = new javax.swing.JTextField();
        severityCB = new javax.swing.JComboBox<>();
        sendalertBT = new javax.swing.JButton();
        alertLBL = new javax.swing.JLabel();
        panelLocator = new javax.swing.JPanel();
        searchLBL = new javax.swing.JLabel();
        searchTF = new javax.swing.JTextField();
        shelterLBL = new javax.swing.JLabel();
        shelterTF = new javax.swing.JTextField();
        shelterBT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panelDamage = new javax.swing.JPanel();
        locationLBL = new javax.swing.JLabel();
        locationTF = new javax.swing.JTextField();
        descriptionLBL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTA = new javax.swing.JTextArea();
        submitBT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAlert.setBackground(new java.awt.Color(190, 218, 204));

        alertmsgLBL.setText("Alert Message:");

        severityLBL.setText("Severity:");

        alertmsgTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertmsgTFActionPerformed(evt);
            }
        });

        severityCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "High" }));
        severityCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                severityCBActionPerformed(evt);
            }
        });

        sendalertBT.setText("Send Alert");
        sendalertBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendalertBTActionPerformed(evt);
            }
        });

        alertLBL.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        alertLBL.setText("Alert");

        javax.swing.GroupLayout panelAlertLayout = new javax.swing.GroupLayout(panelAlert);
        panelAlert.setLayout(panelAlertLayout);
        panelAlertLayout.setHorizontalGroup(
            panelAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlertLayout.createSequentialGroup()
                .addGroup(panelAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlertLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panelAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alertmsgLBL)
                            .addComponent(severityLBL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAlertLayout.createSequentialGroup()
                                .addComponent(severityCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendalertBT))
                            .addComponent(alertmsgTF, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelAlertLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(alertLBL)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panelAlertLayout.setVerticalGroup(
            panelAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlertLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(alertLBL)
                .addGap(18, 18, 18)
                .addGroup(panelAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alertmsgLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alertmsgTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(panelAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(severityCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendalertBT)
                    .addComponent(severityLBL))
                .addGap(10, 10, 10))
        );

        panelLocator.setBackground(new java.awt.Color(255, 255, 255));

        searchLBL.setText("Enter County:");

        searchTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTFActionPerformed(evt);
            }
        });

        shelterLBL.setText("Nearest Shelter:");

        shelterTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shelterTFActionPerformed(evt);
            }
        });

        shelterBT.setText("Find Shelter");
        shelterBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shelterBTActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("Locator");

        javax.swing.GroupLayout panelLocatorLayout = new javax.swing.GroupLayout(panelLocator);
        panelLocator.setLayout(panelLocatorLayout);
        panelLocatorLayout.setHorizontalGroup(
            panelLocatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLocatorLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelLocatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLocatorLayout.createSequentialGroup()
                        .addComponent(shelterLBL)
                        .addGroup(panelLocatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLocatorLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(shelterBT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelLocatorLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(shelterTF))))
                    .addGroup(panelLocatorLayout.createSequentialGroup()
                        .addComponent(searchLBL)
                        .addGap(18, 18, 18)
                        .addGroup(panelLocatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchTF)
                            .addGroup(panelLocatorLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(36, 36, 36))
        );
        panelLocatorLayout.setVerticalGroup(
            panelLocatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLocatorLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(panelLocatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLBL)
                    .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLocatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shelterLBL)
                    .addComponent(shelterTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(shelterBT)
                .addContainerGap())
        );

        panelDamage.setBackground(new java.awt.Color(240, 214, 175));

        locationLBL.setText("Location:");

        locationTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationTFActionPerformed(evt);
            }
        });

        descriptionLBL.setText("Description:");

        descriptionTA.setColumns(20);
        descriptionTA.setRows(5);
        jScrollPane1.setViewportView(descriptionTA);

        submitBT.setText("Submit Damage");
        submitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBTActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Damage");

        javax.swing.GroupLayout panelDamageLayout = new javax.swing.GroupLayout(panelDamage);
        panelDamage.setLayout(panelDamageLayout);
        panelDamageLayout.setHorizontalGroup(
            panelDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDamageLayout.createSequentialGroup()
                .addGroup(panelDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDamageLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(panelDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(locationLBL)
                            .addComponent(descriptionLBL))
                        .addGap(32, 32, 32)
                        .addGroup(panelDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(submitBT)
                            .addComponent(locationTF, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(panelDamageLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDamageLayout.setVerticalGroup(
            panelDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDamageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locationLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitBT)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAlert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelLocator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDamage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAlert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLocator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDamage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alertmsgTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertmsgTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alertmsgTFActionPerformed

    private void severityCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_severityCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_severityCBActionPerformed

    private void shelterTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shelterTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shelterTFActionPerformed

    private void shelterBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shelterBTActionPerformed
        // TODO add your handling code here:
        Locator locator = new Locator();
        String shelter = locator.findShelterByCounty(searchTF.getText());
        
        shelterTF.setText(shelter);
        JOptionPane.showMessageDialog(null,"Nearest shelter: " + shelter);
    }//GEN-LAST:event_shelterBTActionPerformed

    private void locationTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationTFActionPerformed

    private void submitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBTActionPerformed
        // TODO add your handling code here:
        String loc = locationTF.getText();
        String desc = descriptionTA.getText();
        
        // display message to user
        JOptionPane.showMessageDialog(null, "Damage submitted!\nLocation: " + loc + "\nDescription: " + desc);
    }//GEN-LAST:event_submitBTActionPerformed

    private void sendalertBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendalertBTActionPerformed
        // TODO add your handling code here:
        String msg = alertmsgTF.getText();
        String severity = (String) severityCB.getSelectedItem();
        
        // display message to user
        JOptionPane.showMessageDialog(null, "Alert sent! \nMessage: " + msg + "\nSeverity: " + severity);
    }//GEN-LAST:event_sendalertBTActionPerformed

    private void searchTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ActSafeForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertLBL;
    private javax.swing.JLabel alertmsgLBL;
    private javax.swing.JTextField alertmsgTF;
    private javax.swing.JLabel descriptionLBL;
    private javax.swing.JTextArea descriptionTA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel locationLBL;
    private javax.swing.JTextField locationTF;
    private javax.swing.JPanel panelAlert;
    private javax.swing.JPanel panelDamage;
    private javax.swing.JPanel panelLocator;
    private javax.swing.JLabel searchLBL;
    private javax.swing.JTextField searchTF;
    private javax.swing.JButton sendalertBT;
    private javax.swing.JComboBox<String> severityCB;
    private javax.swing.JLabel severityLBL;
    private javax.swing.JButton shelterBT;
    private javax.swing.JLabel shelterLBL;
    private javax.swing.JTextField shelterTF;
    private javax.swing.JButton submitBT;
    // End of variables declaration//GEN-END:variables
}
